<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <RootNamespace>Scada.Web.Plugins.PlgMimShapesJP.View</RootNamespace>
    <Authors>Yuriy Pradius</Authors>
    <Company>Community Rapid Software</Company>
    <Product>Rapid SCADA</Product>
    <Copyright>Copyright © 2026</Copyright>
    <Version>6.5.0</Version>
    <AssemblyVersion>6.5.0.0</AssemblyVersion>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="ScadaCommon">
      <HintPath>..\Libraries\ScadaCommon.dll</HintPath>
    </Reference>
    <Reference Include="ScadaWebCommon">
      <HintPath>..\Libraries\ScadaWebCommon.dll</HintPath>
    </Reference>
  </ItemGroup>
  <Import Project="..\PlgMimShapesJP.Shared\PlgMimShapesJP.Shared.projitems" Label="Shared" />
</Project>
