name: .NET Build All Drivers

on:
  push:
    branches: [ "master" ]
    paths:
      - 'OpenDrivers/**'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'OpenDrivers/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest  # Переключено на Windows

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # DrvDDEJP
    - name: Restore DrvDDEJP
      run: dotnet restore OpenDrivers/DrvDDEJP/DrvDDEJP.sln
    - name: Build DrvDDEJP
      run: dotnet build OpenDrivers/DrvDDEJP/DrvDDEJP.sln --configuration Release --no-restore

    # DrvDbImportPlus
    - name: Restore DrvDbImportPlus
      run: dotnet restore OpenDrivers/DrvDbImportPlus_v6/DrvDbImportPlus.sln
    - name: Build DrvDbImportPlus
      run: dotnet build OpenDrivers/DrvDbImportPlus_v6/DrvDbImportPlus.sln --configuration Release --no-restore

    # DrvDebug
    - name: Restore DrvDebug
      run: dotnet restore OpenDrivers/DrvDebug_v6/DrvDebug.sln
    - name: Build DrvDebug
      run: dotnet build OpenDrivers/DrvDebug_v6/DrvDebug.sln --configuration Release --no-restore

    # DrvFreeDiskSpaceJP
    - name: Restore DrvFreeDiskSpaceJP
      run: dotnet restore OpenDrivers/DrvFreeDiskSpaceJP_v6/DrvFreeDiskSpaceJP.sln
    - name: Build DrvFreeDiskSpaceJP
      run: dotnet build OpenDrivers/DrvFreeDiskSpaceJP_v6/DrvFreeDiskSpaceJP.sln --configuration Release --no-restore

    # DrvFtpJP
    - name: Restore DrvFtpJP
      run: dotnet restore OpenDrivers/DrvFtpJP_v6/DrvFtpJP.sln
    - name: Build DrvFtpJP
      run: dotnet build OpenDrivers/DrvFtpJP_v6/DrvFtpJP.sln --configuration Release --no-restore

    # DrvPingJP
    - name: Restore DrvPingJP
      run: dotnet restore OpenDrivers/DrvPingJP_v6/DrvPingJP.sln
    - name: Build DrvPingJP
      run: dotnet build OpenDrivers/DrvPingJP_v6/DrvPingJP.sln --configuration Release --no-restore

    # DrvTelnetJP
    - name: Restore DrvTelnetJP
      run: dotnet restore OpenDrivers/DrvTelnetJP_v6/DrvTelnetJP.sln
    - name: Build DrvTelnetJP
      run: dotnet build OpenDrivers/DrvTelnetJP_v6/DrvTelnetJP.sln --configuration Release --no-restore
